// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpscgotigzaqmbgnxcxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwc2Nnb3RpZ3phcW1iZ254Y3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQzNjUsImV4cCI6MjA2NTUwMDM2NX0.VFBlPCAXdRK4B9WNDXcH0MSt638Yk0Qwg46AXl-IRVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);